### ISSUE TITLE
SSL connections to OFTC not working

### ISSUE THREAD

**Issue by waddlesplash** [TkTech/notifico#210]
Starting some time in the past few days, connections to irc.oftc.net:6697 no longer seem to deliver messages. I changed one today to use unsecured 6667 and messages are now being posted again. Strangely, there is still a `Not-ff83` in at least one of the channels but it doesn't seem to be posting any messages (instead the posted messages come from `botifico`.)

**Comment by waddlesplash** [comment]
Perhaps this may be related to the most recent news item on OFTC's front page?

> October 2022
>
>    OFTC wants to upgrade the services in use to the Atheme variant. One user visible change will be the uniqueness of SSL cert fingerprints for accounts. If you are using SSL CertFP to identify to your accounts, please review the fingerprints associated with your account(s) and ensure that they are not duplicated between your accounts. This only applies if you have multiple separate accounts using the same fingerprint. Linked/grouped nicks are only a single account.
>
>    We intend to remove any remaining duplicate fingerprint entries on 2022-11-22. The removal algorithm will delete duplicates from all but the most recently used account.

**Comment by TkTech** [comment]
The old `Not-XXX` bots are hanging around because the old n.tkte.ch (AWS) is still up and running in parallel to the new n.tkte.ch (which is using `botifico` in case we needed to rollback.) So, you might see both for a few weeks.

> OFTC wants to upgrade the services in use to the Atheme variant. One user visible change will be the uniqueness of SSL cert fingerprints for accounts. If you are using SSL CertFP to identify to your accounts, please review the fingerprints associated with your account(s) and ensure that they are not duplicated between your accounts. This only applies if you have multiple separate accounts using the same fingerprint. Linked/grouped nicks are only a single account.

Interesting... I'll look into this. The upcoming version of notifico makes it much easier to debug these things and exposes network status issues to the end user but it's not quite ready yet.

**Comment by q66** [comment]
at the moment even non-ssl oftc does not seem to work for me

**Comment by TkTech** [comment]
Sorry for the stability issues! There's a race condition in the new bots I was just too busy to fix during the week. Works like this:

- On OFTC, Haiku is one of the busiest projects, and so likely to be the event that causes us to initially connect to OFTC
- One of Haiku's sub-projects has two channels configured on OFTC
  - One channel uses SSL
  - One channel uses non-SSL
 - When we're not already connected to OFTC, Haiku triggers a webhook which causes us to try joining both SSL and non-SSL at the _exact same time_
 - OFTC reasonably doesn't like this and will randomly axe one connection because we're joining multiple times far too quickly
 - OFTC axes this connection in a way that doesn't cause the network to get unlisted from the internal manager, so it'll keep thinking it's valid and send it messages instead of reconnecting.

What's the fix?

- Ensure that the network getting disconnected like this removes it from the internal list of connected networks.
- De-duplicate SSL/non-SSL connections when they're _pending_, not just when they're completely connected.
- Internally, run `notifico irc merge 124 68` to merge the non-SSL oftc network into the SSL one

I'm working on this now.
